### PR TITLE
Transfer money

### PR DESCRIPTION
**Pull request by NicoHood**
This PR is based on #78 . I will rebase once this PR got merged.

It adds basic money transfer buttons between users, using the current/old API. There are some limitations along with some bugs:
* ~~The backend does not report transaction limitations. Thatswhy an invalid transfer can only be recognized after trying it. See https://github.com/hackerspace-bootstrap/strichliste/issues/275~~ -> solved with new backend
* ~~Because of no proper transfer backend API this frontend does substract, then adds money~~ -> used new proper api
* ~~**An issue related to this is that even though the substraction fails, the addition will always happen. This is a bug in the code, that I was unable to solve yet. It is marked with a `TODO`.**~~ -> Solved with new backend api

A proper transfer backend API ~~should be~~ was implemented. ~~However this can be used as workaround in the meantime. I recommend setting the account transfer limits to infinitive value or at least make sure that subtracting transfers are always lower than addition transfers.~~

Translation is also required.

### CODE REVIEW

**Comment by NicoHood** [comment]
Some pictures for more illustration:

screenshot from 2018-01-27 02-40-33

screenshot from 2018-01-27 02-40-52

**Comment by schinken** [comment]
Thanks for that feature, but also I would like that feature disabled by default through settings. In a default install, there should be no third row, even if it works technically.

Could you add a settings parameter and just hide the third row?

**Comment by NicoHood** [comment]
Of course, I will work on that.

**Comment by schinken** [comment]
Btw, that might not be that hard after all. You just need to add some ng-if to the html tags wrapping the buttons and on the table head and column. Like ng-if="settings.wireTransfer"

**Comment by NicoHood** [comment]
I've added the suggested option. However the open TODO needs to get fixed. If removing the money does not work, adding should be cancelled. Alternatively I will try to implement a transfer API now.

**Comment by NicoHood** [comment]
This PR should be merged once the comment PR was merged. I will then rebase, so the diff is smaller.

**Comment by NicoHood** [comment]
I have rebased the PR. It would be nice if you can give this and the backend PR a quick review :)

**Pull request merged**
